"""initial migration

Revision ID: cd7c6e63ceaa
Revises: 
Create Date: 2026-07-26 16:17:17.921700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7c6e63ceaa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campuses_id'), 'campuses', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('connection_type', sa.String(length=20), nullable=False),
    sa.Column('ssh_username', sa.String(length=100), nullable=True),
    sa.Column('ssh_key_path', sa.String(length=500), nullable=True),
    sa.Column('tls_cert_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_packets', sa.Integer(), nullable=False),
    sa.Column('total_alerts', sa.Integer(), nullable=False),
    sa.Column('network_load', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_id'), 'nodes', ['id'], unique=False)
    op.create_table('IntrusionsAlerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('destination_ip', sa.String(length=45), nullable=False),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('is_manual_block', sa.Boolean(), nullable=False),
    sa.Column('validated_by_admin', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_IntrusionsAlerts_alert_type'), 'IntrusionsAlerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_IntrusionsAlerts_destination_ip'), 'IntrusionsAlerts', ['destination_ip'], unique=False)
    op.create_index(op.f('ix_IntrusionsAlerts_id'), 'IntrusionsAlerts', ['id'], unique=False)
    op.create_index(op.f('ix_IntrusionsAlerts_protocol'), 'IntrusionsAlerts', ['protocol'], unique=False)
    op.create_index(op.f('ix_IntrusionsAlerts_severity'), 'IntrusionsAlerts', ['severity'], unique=False)
    op.create_index(op.f('ix_IntrusionsAlerts_source_ip'), 'IntrusionsAlerts', ['source_ip'], unique=False)
    op.create_index(op.f('ix_IntrusionsAlerts_timestamp'), 'IntrusionsAlerts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_IntrusionsAlerts_timestamp'), table_name='IntrusionsAlerts')
    op.drop_index(op.f('ix_IntrusionsAlerts_source_ip'), table_name='IntrusionsAlerts')
    op.drop_index(op.f('ix_IntrusionsAlerts_severity'), table_name='IntrusionsAlerts')
    op.drop_index(op.f('ix_IntrusionsAlerts_protocol'), table_name='IntrusionsAlerts')
    op.drop_index(op.f('ix_IntrusionsAlerts_id'), table_name='IntrusionsAlerts')
    op.drop_index(op.f('ix_IntrusionsAlerts_destination_ip'), table_name='IntrusionsAlerts')
    op.drop_index(op.f('ix_IntrusionsAlerts_alert_type'), table_name='IntrusionsAlerts')
    op.drop_table('IntrusionsAlerts')
    op.drop_index(op.f('ix_nodes_id'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_campuses_id'), table_name='campuses')
    op.drop_table('campuses')
    # ### end Alembic commands ###
